# 1. Create the following NumPy arrays: 

In [2]:
import numpy as np

In [3]:
# a) A 1-D array called zeros having 10 elements and all the elements are set to zero.
zeros = np.zeros(10,dtype=int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


In [4]:
# b) A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
vowels = np.array(['a','e','i','o','u'])
print(vowels)

['a' 'e' 'i' 'o' 'u']


In [5]:
# c) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and  dtype as int.
ones = np.ones((2,5),dtype=int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
# d) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: i. 2.7, -2, -19, ii. 0, 3.4, 99.9, iii. 10.6, 0, 13 
myarray1 = np.array([[2.7, -2, -19],[0, 3.4, 99.9],[10.6, 0, 13]])
print(myarray1)

[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


In [43]:
# e) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4,step size 4 and dtype as float.
myarray2 = np.arange(start=4, stop=61, step=4, dtype=float)
myarray2.resize(3,5)
print(myarray2)



[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


# Using the arrays created in the above, write NumPy commands for the following:

In [44]:
# a) Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels,ones, myarray1 and myarray2.
print("The dimension of array zeros is",zeros.ndim)
print("The shape of array zeros is",zeros.shape)
print("The size of array zeros is",zeros.size)
print("Data type of the items in zeros array is ",zeros.dtype)
print("The itemsize of array is",zeros.itemsize)

The dimension of array zeros is 1
The shape of array zeros is (10,)
The size of array zeros is 10
Data type of the items in zeros array is  int32
The itemsize of array is 4


In [45]:
print("The dimension of array vowels is",vowels.ndim)
print("The shape of array vowels is",vowels.shape)
print("The size of array vowels is",vowels.size)
print("Data type of the items in vowels array is ",vowels.dtype)
print("The itemsize of array is",vowels.itemsize)

The dimension of array vowels is 1
The shape of array vowels is (5,)
The size of array vowels is 5
Data type of the items in vowels array is  <U1
The itemsize of array is 4


In [46]:
print("The dimension of array ones is",ones.ndim)
print("The shape of array vowels is",ones.shape)
print("The size of array vowels is",ones.size)
print("Data type of the items in ones array is ",ones.dtype)
print("The itemsize of array is",ones.itemsize)

The dimension of array ones is 2
The shape of array vowels is (2, 5)
The size of array vowels is 10
Data type of the items in ones array is  int32
The itemsize of array is 4


In [47]:
print("The dimension of array myarray1 is",myarray1.ndim)
print("The shape of array myarray1 is",myarray1.shape)
print("The size of array myarray1 is",myarray1.size)
print("Data type of the items in myarray1 array is ",myarray1.dtype)
print("The itemsize of array is",myarray1.itemsize)

The dimension of array myarray1 is 2
The shape of array myarray1 is (3, 3)
The size of array myarray1 is 9
Data type of the items in myarray1 array is  float64
The itemsize of array is 8


In [48]:
print("The dimension of array myarray2 is",myarray2.ndim)
print("The shape of array myarray2 is",myarray2.shape)
print("The size of array myarray2 is",myarray2.size)
print("Data type of the items in zeros array is ",myarray2.dtype)
print("The itemsize of array is",myarray2.itemsize)

The dimension of array myarray2 is 2
The shape of array myarray2 is (3, 5)
The size of array myarray2 is 15
Data type of the items in zeros array is  float64
The itemsize of array is 8


In [49]:
# b) Reshape the array ones to have all the 10 elements in a single row. 
ones = np.ones((2,5),dtype=int)
print(ones.reshape(1,10))

[[1 1 1 1 1 1 1 1 1 1]]


In [50]:
# c) Display the 2nd and 3rd element of the array vowels. 
print(vowels[1],vowels[2])

e i


In [51]:
# d) Display all elements in the 2nd and 3rd row of the array myarray1. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
print(myarray1[1:3])

[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]


In [52]:
# e) Display the elements in the 1st and 2nd column of the array myarray1.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
print(myarray1[0:3,0:2])

[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]


In [53]:
# f) Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
myarray1 = np.array([[2.7,-2,19],[0,3.4,99.9],[10.6,0,13]])
print(myarray1[1:3,0:3])

[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]


In [54]:
# g) Reverse the array of vowels.
vowels = np.array(['a','e','i','o','u'])
print(vowels[::-1])

['u' 'o' 'i' 'e' 'a']


In [55]:
# h) Divide all elements of array ones by 3. 
ones = np.ones((2,5),dtype=int)
print(ones/3)

[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]


In [57]:
# i) Add the arrays myarray1 and myarray2.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
print(np.add(myarray1,myarray2))

[[  6.7   6.   -7. ]
 [ 16.   23.4 123.9]
 [ 38.6  32.   49. ]]


In [68]:
 # j) Subtract myarray1 from myarray2 and store the result in a new array
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray3=np.subtract(myarray2,myarray1)
print(myarray3)

[[  1.3  10.   31. ]
 [ 16.   16.6 -75.9]
 [ 17.4  32.   23. ]]


In [59]:
# k) Multiply myarray1 and myarray2 element wise. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,40,4,dtype=float)
myarray2.resize(3,3)
myarray3=np.matmul(myarray1, myarray2)
print(myarray3)

[[-553.2 -626.4 -699.6]
 [2851.6 3264.8 3678. ]
 [ 406.4  500.8  595.2]]


In [60]:
# l) Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray3 = myarray2 @ myarray1
print(myarray3)

[[ 138.    19.2  879.2]
 [ 297.6   36.  2006. ]
 [ 457.2   52.8 3132.8]]


In [61]:
# m) Divide myarray1 by myarray2. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
print(myarray1 / myarray2)

[[ 0.675      -0.25       -1.58333333]
 [ 0.          0.17        4.1625    ]
 [ 0.37857143  0.          0.36111111]]


In [62]:
# n) Find the cube of all elements of myarray1 and divide the resulting array by 2.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarraycube = myarray1 ** 3
print(myarraycube/2)

[[ 9.841500e+00 -4.000000e+00 -3.429500e+03]
 [ 0.000000e+00  1.965200e+01  4.985015e+05]
 [ 5.955080e+02  0.000000e+00  1.098500e+03]]


In [63]:
# o) Find the square root of all elements of myarray2 and divide the resulting array by 2. The result should be rounded to two places of decimals.
myarray2 = np.arange(4,61,4,dtype=float)
myarray2.resize(3,5)
arraysqrt = np.sqrt(myarray2)
newarraysqrt = arraysqrt/2
print(np.around(newarraysqrt,2))

[[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]]


In [64]:
# p) Find the transpose of ones and myarray2.
ones = np.ones((2,5),dtype=int)
print(ones.transpose())

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [65]:
myarray2 = np.arange(4,61,4,dtype=float)
myarray2.resize(3,5)
print(myarray2.transpose())

[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]


In [30]:
# q) Sort the array vowels in reverse. 
vowels = np.array(['a','e','i','o','u'])
print(vowels[ : : -1])

['u' 'o' 'i' 'e' 'a']


In [31]:
# r) Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray1.sort()
print(myarray1)

[[-19.   -2.    2.7]
 [  0.    3.4  99.9]
 [  0.   10.6  13. ]]


In [32]:
# s) Use NumPy. split() to split the array myarray2 into 5 arrays column wise. Store your resulting arrays in myarray2A, myarray2B, myarray2C, myarray2D and myarray2E. Print the arrays myarray2A, myarray2B, myarray2C, myarray2D and myarray2E
myarray2 = np.arange(4,61,4,dtype=float)
myarray2.resize((3,5))
myarray2A, myarray2B, myarray2C, myarray2D, myarray2E = np.split(myarray2, indices_or_sections=5, axis=1)
print(myarray2A, myarray2B, myarray2C, myarray2D, myarray2E)

[[ 4.]
 [24.]
 [44.]] [[ 8.]
 [28.]
 [48.]] [[12.]
 [32.]
 [52.]] [[16.]
 [36.]
 [56.]] [[20.]
 [40.]
 [60.]]


In [33]:
# t) Split the array zeros at array index 2, 5, 7, 8 and store the resulting arrays in zerosA, zerosB, zerosC and zerosD and print them.
zeros = np.zeros(10,dtype=int)
zerosA, zerosB, zerosC, zerosD, _ = np.split(zeros,indices_or_sections=(2,5,7,8))
print(zerosA, zerosB, zerosC, zerosD)

[0 0] [0 0 0] [0 0] [0]


In [66]:
# u) Concatenate the arrays myarray2A, myarray2B and myarray2C into an array having 3 rows and 3 columns
myarray2 = np.arange(4,61,4,dtype=float)
myarray2.resize(3,5)
print(np.concatenate((myarray2A, myarray2B, myarray2C),axis=1))

[[ 4.  8. 12.]
 [24. 28. 32.]
 [44. 48. 52.]]


In [35]:
# v) Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

myarray4 = np.arange(start=-1, stop=9.5, step=0.25, dtype=float)
myarray4 = myarray4.reshape((14,3))
print(myarray4)

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]


# w) Using the myarray4 created in the above questions, write commands for the following: 

In [36]:
# i. Find the sum of all elements. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.sum())

173.25


In [37]:
# ii. Find the sum of all elements row wise.
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.sum(axis=1))

[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]


In [38]:
# iii. Find the sum of all elements column wise. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.sum(axis=0))

[54.25 57.75 61.25]


In [39]:
# iv. Find the max of all elements. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.max())

9.25


In [40]:
# v. Find the min of all elements in each row.
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.max(axis=1))

[-0.5   0.25  1.    1.75  2.5   3.25  4.    4.75  5.5   6.25  7.    7.75
  8.5   9.25]


In [41]:
# vi. Find the mean of all elements in each row. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.mean(axis=1))

[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]


In [42]:
# vii. Find the standard deviation column wise.
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
print(myarray4.std(axis=0))

[3.02334666 3.02334666 3.02334666]
