In [1]:
#Create multi-dimensional arrays and find its shape and dimension
import numpy as np
x = np.array([[1,2,3],[4,5,6]], np.int32)
type(x)
x.shape
x.dtype

dtype('int32')

In [9]:
#Create a matrix full of zeros and ones
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [12]:
#Reshape and flatten data in the array
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np.reshape(a, (3,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
#Reshape and flatten data in the array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('flattening array')
print(a.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
flattening array
[1 2 3 4 5 6 7 8 9]


In [23]:
#Apply indexing and slicing on array
a2 = np.array([[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],[25,26,27,28,29]])
print(a2[2,2:4])
print(a2[:, 1])

[22 23]
[11 16 21 26]


In [31]:
#Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation
#MEAN FUNCTION
a = np.array([[1,2],[3,4]])
mean=np.mean(a)
print(mean)
b=np.mean(a, axis=0)
print(b)
c=np.mean(a,axis=1)
print(c)

2.5
[2. 3.]
[1.5 3.5]


In [38]:
#MEDIAN STATISTICAL FUNCTION
a = np.array([[10,7,4], [3,2,1]])
a
b=np.median(a)
print(b)
c=np.median(a, axis=0)
print(c)
d=np.median(a,axis=1)
print(d)

3.5
[6.5 4.5 2.5]
[7. 2.]


In [41]:
#standard deviation in statistical function
a = np.array([[1,2],[3,4]])
b=np.std(a)
print(b)
c=np.std(a, axis=0)
print(c)
d=np.std(a, axis=1)
print(d)

1.118033988749895
[1. 1.]
[0.5 0.5]


In [48]:
#minmum value in the array
a = np.arange(4).reshape((2,2))
a
b = np.amin(a)
print(b)
c = np.amin(a, axis=0)
print(c)
d = np.amin(a, axis=1)
print(d)

0
[0 1]
[0 2]


In [53]:
#maximum value in the array
a = np.arange(4).reshape((2,2))
a
b=np.amax(a)
print(b)
c=np.amax(a, axis=0)
print(c)
d=np.amax(a, axis=1)
print(d)

3
[2 3]
[1 3]


In [56]:
#Append data vertically and horizontally
a = np.array([1,2,3])
b = np.array([4,5,6])
c=np.vstack((a,b))
print(c)
d=np.hstack((a,b))
print(d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
