In [1]:
# 3(a) Dot and matrix product of two arrays
import numpy as np
np.dot(3,4)
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [6]:
#3(b)Compute the Eigen values of a matrix
from numpy import linalg as LA
w, v = LA.eig(np.array([[1, -1], [1, 1]]))
w; v

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

In [7]:
#3(c)Solve a linear matrix equation such as 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8.
a = np.array([[3, 1],[1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a,b)
print(x)

[2. 3.]


In [10]:
#3(d)Compute the multiplicative inverse of a matrix
import numpy as np
m = np.matrix([[1, 0, 0], [1, 1, 0], [0, 0, 1]])
temp = np.linalg.inv(m)
print(temp)

[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]


In [22]:
#3(e)Compute the rank of a matrix
from numpy.linalg import matrix_rank 
matrix_rank(np.eye(4))
I=np.eye(4); I[-1,-1] = 0.
rank=matrix_rank(I)
print(I)
print(rank)
ones=matrix_rank(np.ones((4,)))
print(ones)
zeros=matrix_rank(np.zeros((4,)))
print(zeros)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
3
1
0


In [24]:
#3(f)Compute the determinant of an array.
import numpy as np
a = np.array([[1,2], [3,4]])
print (np.linalg.det(a))

-2.0000000000000004


In [26]:
#3(F)Compute the determinant of an array.
b = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(b)
print (np.linalg.det(b))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
