In [2]:
import numpy as np
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
vowels = np.array(list('aeiou'))
print(vowels)

['a' 'e' 'i' 'o' 'u']


In [3]:
ones = np.ones((2,5),dtype = int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [49]:
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
print(myarray1)

[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


In [41]:
myarray2 = np.arange(4,61,4,float).reshape(3,5)
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


In [13]:
np.shape(myarray1)

(3, 3)

In [14]:
np.size(myarray1)

9

In [18]:
print(myarray1.dtype)

float64


In [19]:
print(myarray2.dtype)

float64


In [21]:
np.size(ones)

5

In [22]:
np.size(vowels)

5

In [23]:
np.size(zeros)

10

In [24]:
print(myarray1.ndim)

2


In [25]:
print(myarray2.ndim)

2


In [26]:
np.shape(ones)

(2, 5)

In [27]:
np.shape(vowels)

(5,)

In [28]:
np.shape(zeros)

(10,)

In [36]:
print(vowels.ndim)

1


In [37]:
print(ones.ndim)

2


In [38]:
print(zeros.ndim)

1


In [44]:
ones.reshape((10))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
vowels[[1,2]]

array(['e', 'i'], dtype='<U1')

In [47]:
myarray1[[1,2]]

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

In [50]:
myarray1.T[[0,1]]

array([[ 2.7,  0. , 10.6],
       [-2. ,  3.4,  0. ]])

In [54]:
myarray1[::-1]

array([[ 10.6,   0. ,  13. ],
       [  0. ,   3.4,  99.9],
       [  2.7,  -2. , -19. ]])

In [57]:
myarray1.T[[0,0],[1,0]]

array([0. , 2.7])

In [16]:
myarray1 + myarray2

[[2.7, -2, -19],
 [0, 3.4, 99.9],
 [10.6, 0, 65],
 [4, 8, 12],
 [24, 28, 32],
 [44, 48, 52]]

In [19]:
print(myarray1)

[[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 65]]


In [21]:
myarray1 ** 3

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'